### ISSUE TITLE
Main thread freeze on run?

### ISSUE THREAD

**Issue by leopoldhub** [Doridian/LuaJS#141]
Hi, it seems that the main thread (and promises/async parallel functions) 
are frozen until the end of the run function.

Here is a small script to demonstrate:

```js
const {LuaJS} = require("@doridian/luajs");

let i = 0;

async function x() {
    i = (i+1)%10;
    console.log("GENERATE", i)
    setTimeout(() => {x()}, 100)
}

x()

LuaJS.newState().then(async (L) => {
    const _G = L.getGlobalTable();
    _G.set("myLib", {
        getI: function () {
            return i;
        }
    });
    L.run(`
    while true do
        print(myLib:getI())
    end
    `);
});
```

here are the execution logs:

```
GENERATE 1
1
1
1
1
1
...
```

As you can see, the "x" function is only executed once.
if you remove the while condition, "x" will continue its normal execution after "run".

Would it be possible to run the lua worker in a new separate thread to avoid this behavior?

Thanks for your great work, have a nice day.

**Comment by leopoldhub** [comment]
Small update here, I tested it in browser and it have the same behavior.

```html
<!DOCTYPE html>
<html>
<head>
    <script type="module" src="./node_modules/@doridian/luajs/dist/luajs.mjs"></script>
    <script type="module">
        import emscriptenInit from './node_modules/@doridian/luajs/dist/luajs.mjs';
        const LuaJS = await emscriptenInit();

        LuaJS.newState().then(async (L) => {
            await L.enableLuaScriptTags(document);
        });

        let i = 0;

        async function x() {
            i = (i + 1) % 10;
            console.log(i);
            setTimeout(() => {
                x();
            }, 100);
        }

        x();
    </script>
    <script type="text/lua">
        while true do
            print("a")
        end
    </script>
</head>
</html>
```

**Comment by Doridian** [comment]
@leopoldhub Yes, that is correct, Javascript is fundamentally single-threaded and while Lua is running, the "main thread" is busy because WASM also just runs in the main thread by necessity.

You can load LuaJS in another context/process/thread yourself by using whatever such API you have available in your JS engine (browsers have [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) for example). This can't be implemented directly as that would make it impossible to pass things such as functions between Lua and JS (since you can't just call into another JS state) without a very complex RPC maybe

**Comment by leopoldhub** [comment]
Hi @Doridian 

Thanks for the quick response.
Would it be possible to have a function (e.g. js.release(xxx)) that would pause the Lua process for a certain amount of ms?

That way we could:
1. pause/wait the lua script for a certain amount of time (a kind of sleep)
2. "Simulate" multi-threading and control how much cpu time we want to give our processes

> browsers have [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) for example

Thanks for the tip, I will try to experiment with them and keep you informed.

**Comment by Doridian** [comment]
Even the closest equivalent available in emscripten's API [emscripten_sleep_with_yield](https://docs.huihoo.com/emscripten/emscripten-site/docs/api_reference/emscripten.h.html#c.emscripten_sleep_with_yield) explicitly states it will continue to block the main thread and only allow some async code to run and also calls out using the method can produce "confusing execution order"
