### ISSUE TITLE
no luajs.js file

### ISSUE THREAD

**Issue by HanzieUWU** [Doridian/LuaJS#19]
There is no luajs.js file even after installing

**Comment by Doridian** [comment]
@HanzieUWU Which commands did you run?
After the `npm install && npm run clean && npm run build` commands, there should be a `luajs.js` file inside of the `dist/` folder (along with luajs.wasm and other files)

**Comment by HanzieUWU** [comment]
I ran `npm install && npm run clean && npm run build` and everything was successful, yet it still did not work. Im on windows 10

**Comment by HanzieUWU** [comment]
> @HanzieUWU Which commands did you run? After the `npm install && npm run clean && npm run build` commands, there should be a `luajs.js` file inside of the `dist/` folder (along with luajs.wasm and other files)
> 
> //EDIT: Please post the commands and their output to help me understand what went wrong.

The error is: "'emmake' is not recognized as an internal or external command,
operable program or batch file."

**Comment by Doridian** [comment]
> > @HanzieUWU Which commands did you run? After the `npm install && npm run clean && npm run build` commands, there should be a `luajs.js` file inside of the `dist/` folder (along with luajs.wasm and other files)
> > //EDIT: Please post the commands and their output to help me understand what went wrong.
> 
> The error is: "'emmake' is not recognized as an internal or external command, operable program or batch file."

As the readme says, you need emscripten installed. Please follow the instructions for your platform/OS to install it.
On Windows the best option is usually to use the Docker image and install NodeJS into it.
