### ISSUE TITLE
Defining classes?

### ISSUE THREAD

**Issue by Frityet** [Doridian/LuaJS#25]
How would classes be defined? I want to create custom web components with lua, but I am not sure how to go about doing it, maybe there should be some syntax like

```lua
local xml_gen = require("xml-generator")
local xml = xml_gen.xml
---@diagnostic disable-next-line: undefined-global
local js = js
local this = js.global

local WordCount = js.class "WordCount" (this.HTMLParagraphElement) {
    observedAttributes = { "text" },

    constructor = function (self)
        self:super()
        self:attachShadow { mode = "open" }
        self.shadowRoot:appendChild(xml.div {
            xml.p {id="text"},
            xml.p {id="wordCount"}
        })
    end,

    connectedCallback = function (self)
        print("connected")
    end
}
```

Or better, something simpler

**Comment by SimonSchick** [comment]
JS classes are just syntax sugar for prototype chains, you can likely build this yourself, I don't think this is in scope for this library?

**Comment by Frityet** [comment]
> JS classes are just syntax sugar for prototype chains, you can likely build this yourself, I don't think this is in scope for this library?

Ah, I'm not familiar with JS, where can I find documentation for that?

**Comment by Frityet** [comment]
> JS classes are just syntax sugar for prototype chains, you can likely build this yourself, I don't think this is in scope for this library?

The problem is that Lua functions don't have `.prototype`, and you can't index them to add that, so i am unsure what to do

**Comment by Frityet** [comment]
Fixed, I just made a JS function for defining classes
