### ISSUE TITLE
Using luarocks modules

### ISSUE THREAD

**Issue by Frityet** [Doridian/LuaJS#4]
Hello, I would like to use luarocks (the lua package manager) modules with this project. I have luarocks setup to install the modules into `./lua_modules/share/lua/5.4/?.lua`, and I set a script to do that

```html
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Test</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script type="text/javascript" src='luajs.js'></script>

    <script>
        Module.ready.then(() => {
            const L = new Module.State();
            L.enableLuaScriptTags(document);
        });
    </script>

    <script type="text/lua">
        package.path="./lua_modules/share/lua/5.4/?.lua;./lua_modules/share/lua/5.4/?/init.lua;"..package.path
    </script>

    <script type="text/lua" src="test.lua"></script>
</head>
```

However, it still cannot find the modules, what could I do to fix this?

**Comment by Doridian** [comment]
Currently, the way the "filesystem" works is that the `fsroot` folder is what the root of your filesystem will be when you compile LuaJS. All files are embedded into the final artifact and loaded as such.

So you would have to put your Lua modules into `fsroot/lua/modules` and then `emmake make install`, and then they should load (without modifying `package.path`).

This might not be the best option, though, I'll check if I can make a module loader that can actually load URLs and not just embedded files, but that will require some work.

**Comment by Frityet** [comment]
> Currently, the way the "filesystem" works is that the `fsroot` folder is what the root of your filesystem will be when you compile LuaJS. All files are embedded into the final artifact and loaded as such.
> 
> So you would have to put your Lua modules into `fsroot/lua/modules` (which will appear as `/lua/modules` in Lua's "filesystem") and then `emmake make clean && emmake make install`, and then they should load (without modifying `package.path`).
> 
> This might not be the best option, though, I'll check if I can make a module loader that can actually load URLs and not just embedded files, but that will require some work.

Thank you so much! I will try that! I am also going to try and make a `package.searcher` function for doing the loading from URLs (I am pretty sure I have access to `fetch` from lua right?

**Comment by Doridian** [comment]
> > Currently, the way the "filesystem" works is that the `fsroot` folder is what the root of your filesystem will be when you compile LuaJS. All files are embedded into the final artifact and loaded as such.
> > So you would have to put your Lua modules into `fsroot/lua/modules` (which will appear as `/lua/modules` in Lua's "filesystem") and then `emmake make clean && emmake make install`, and then they should load (without modifying `package.path`).
> > This might not be the best option, though, I'll check if I can make a module loader that can actually load URLs and not just embedded files, but that will require some work.
> 
> Thank you so much! I will try that! I am also going to try and make a `package.searcher` function for doing the loading from URLs (I am pretty sure I have access to `fetch` from lua right?

You should have access to fetch via `js.global.fetch`. Sadly of course you won't be able to use `async/await` and will have to reply on `.then` and `.catch`. Alternatively you can write the loader mostly in JS and just call out to it from Lua.

**Comment by Frityet** [comment]
> > > Currently, the way the "filesystem" works is that the `fsroot` folder is what the root of your filesystem will be when you compile LuaJS. All files are embedded into the final artifact and loaded as such.
> > > So you would have to put your Lua modules into `fsroot/lua/modules` (which will appear as `/lua/modules` in Lua's "filesystem") and then `emmake make clean && emmake make install`, and then they should load (without modifying `package.path`).
> > > This might not be the best option, though, I'll check if I can make a module loader that can actually load URLs and not just embedded files, but that will require some work.
> > 
> > 
> > Thank you so much! I will try that! I am also going to try and make a `package.searcher` function for doing the loading from URLs (I am pretty sure I have access to `fetch` from lua right?
> 
> You should have access to fetch via `js.global.fetch`. Sadly of course you won't be able to use `async/await` and will have to reply on `.then` and `.catch`. Alternatively you can write the loader mostly in JS and just call out to it from Lua.

Nice! Also, have you tried allowing `dlopen` to be used? I am about to try it now to load a lua library compiled with `emcc`, but im a bit curious if it was already tried

**Comment by Doridian** [comment]
> Nice! Also, have you tried allowing `dlopen` to be used? I am about to try it now to load a lua library compiled with `emcc`, but im a bit curious if it was already tried

I have not played around with `dlopen` or any binary Lua modules.

**Comment by Frityet** [comment]
Im gonna do some testing, also, is there a reason why the git releases of lua are used instead of the `.tar.gz` releases? They have differing makefiles and other changes

**Comment by Doridian** [comment]
> Im gonna do some testing, also, is there a reason why the git releases of lua are used instead of the `.tar.gz` releases? They have differing makefiles and other changes

It was easier to make a git submodule that is pinned to the latest tag of Lua (currently Lua 5.4.6), than making a Makefile automatically download them somehow.

**Comment by Frityet** [comment]
`dlopen` works GREAT! I will make a PR that changes the makefile to support it

**Comment by Doridian** [comment]
> `dlopen` works GREAT! I will make a PR that changes the makefile to support it

That sounds super neat. Looking forward to your PR!

Also I have now added support for `async/await` / Promises in Lua land, so building a package loader that actually `fetch()`-es resources is now fully possible (and likely the next thing to implement)

**Comment by Frityet** [comment]
> > `dlopen` works GREAT! I will make a PR that changes the makefile to support it
> 
> That sounds super neat. Looking forward to your PR!
> 
> Also I have now added support for `async/await` / Promises in Lua land via `js.await(promise)`, so building a package loader that actually `fetch()`-es resources is now fully possible (and likely the next thing to implement)

Thank you so much!!!
