### ISSUE TITLE
using `luajs.js` in a website looks for `/luajs.wasm` and `/luajs.data`, possible to change the search path?

### ISSUE THREAD

**Issue by Frityet** [Doridian/LuaJS#52]
Its much easier if it would be possible for the search path to be customised, as I often have my JS files like that in a `js` folder, and so it still looks in the root dir, even checking the dir the js file is in would be better

**Comment by Doridian** [comment]
I have been looking into this myself, because this makes publishing this as a NodeJS module really annoying.

So far I haven't found a solution, but I'm sure one has to exist...

**Comment by Doridian** [comment]
This should now be fixed :)
