### ISSUE TITLE
Is the README example up to date?

### ISSUE THREAD

**Issue by wqferr** [Doridian/LuaJS#55]
I keep getting `Uncaught SyntaxError: import not found: default` on the line `import emscriptenInit from "./js/luajs.mjs";`

On an unrelated note, I can't seem to put the .wasm and .data files wherever I want, it only finds it if they're in the root of the project.

**Comment by Frityet** [comment]
See #52

**Comment by wqferr** [comment]
It worked! Thank you so much. I'm working on switching the Lua VM from Fengari to this one on a project of mine. I can send you the link to it if you want to include a portfolio / usage list of sorts for LuaJS.

**Comment by Doridian** [comment]
@wqferr Also FYI: On the latest main, a `.data` file is no longer produced. It is now embedded, as a tiny 5kB file is actively worse for load times (and also made the switch to ES6 modules unnecessarily difficult).

If you want, feel free to hand me a link, I might do a portfolio section or something.

**Comment by wqferr** [comment]
Oh that's awesome! Thanks

The app page is hosted on GitHub pages here: https://wqferr.github.io/SimplyComplex/
