### ISSUE TITLE
enableLuaScriptTags throws an exception if the DOM was modified while loading scripts

### ISSUE THREAD

**Issue by wqferr** [Doridian/LuaJS#56]
For my application I need to create 2 logic-only, no display canvases. This causes the Lua tag enabling to stop.

I've managed to weasel my way out of it by wrapping it in a try/catch and while loop, but it's less than ideal, to say the least.

```javascript
            let ok = false;
            // this exception absorbing loop is required because the canvases
            // draw.lua creates throw a wrench in the enableLuaScriptTags processing
            while (!ok) {
                try {
                    await L.enableLuaScriptTags(document);
                    ok = true;
                } catch (e) {}
            }
```

**Comment by Doridian** [comment]
@wqferr This should be fixed in the latest version.

**Comment by wqferr** [comment]
Works perfectly! Thanks for the quick fixes!
