### ISSUE TITLE
Top-level await is not available in configured target environment

### ISSUE THREAD

**Issue by Kinflou** [Doridian/LuaJS#57]
Hello :wave: i installed this package in my svelte shared library, then i imported it and visited the page, the following error occurs
```js
✘ [ERROR] Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

    node_modules/.pnpm/@doridian+luajs@1.0.7/node_modules/@doridian/luajs/util/loader_mjs.mjs:2:14:
      2 │ const LuaJS = await moduleCtor();
        ╵               ~~~~~
```

## How did i add and use this package?
I did `cd shared-compilation` then `pnpm install @doridian/luajs`,
then to use it, in the file `src/lib/wasm/lua/compilation.ts` just imported by doing `import {LuaJS} from "@doridian/luajs"`

## Steps to reproduce the issue (with my repo)
If you don't have pnpm, you can get and install it: https://pnpm.io/installation 

Clone the repository: `git clone https://github.com/ComlineProject/shared-web.git`
Change directory: `cd shared-web/shared-compilation`
Install dependencies: `pnpm install`
Run in dev mode: `pnpm run dev`

Visit http://localhost:5173/wasm-compilers/lua
Error will pop up in the local dev console

**Comment by Doridian** [comment]
Your target is set for too old browser. I assume this is the default target of Playwright (`firefox78` just as an example is basically ancient).

Acording to https://github.com/vitejs/vite/issues/6985#issuecomment-1044375490 you can set `build -> target` to `esnext` in `vite.config.ts`, and that should fix it.

Also see: https://caniuse.com/?search=top%20level%20await (this shows it is supported in any modern browser)

**Comment by Doridian** [comment]
Closing as it is not a problem in LuaJS.
